In [1]:
import numpy as np
from keras.preprocessing import image

Using TensorFlow backend.


In [2]:
import os
from glob import glob

In [3]:
PATH ='./some images'

In [4]:
print(os.listdir(PATH))

['New folder', 'New folder (2)', 'New folder (3)']


In [5]:
labels = []
images_path = []
total = 0

In [6]:
classlabel=1
for fold in (os.listdir(PATH)):
    SOURCE_IMAGES = os.path.join(PATH, fold)

   # 
    folder = glob(os.path.join(SOURCE_IMAGES, "*.jpg"))

    # Prepare labels 

    i = 0
    while i < len(folder):
        labels.append(classlabel)
        images_path.append(folder[i])
        i += 1
        total += 1
    print("Imported "+ str(i) + " images from {}".format(fold))
    classlabel+=1

print( str(total) + " Imported  images in total")

Imported 6 images from New folder
Imported 9 images from New folder (2)
Imported 7 images from New folder (3)
22 Imported  images in total


In [7]:
labels

[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3]

In [8]:
import cv2

In [9]:
X = [] # images as arrays
Y = [] # labels Infiltration or Not_infiltration
WIDTH = 240
HEIGHT = 240
n = 0

for img in images_path:
       
    # Read and resize image
    full_size_image = cv2.imread(img)
    X.append(cv2.resize(full_size_image, (WIDTH,HEIGHT)))
    Y.append(labels[n])
    n += 1

In [10]:
#Saving images datasets as a NPZ files.
np.save("images.npy", X)
np.save("labels.npy", Y)  

In [11]:
X_train = np.load("images.npy")
Y_train = np.load("labels.npy")

In [12]:
Y_train

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3])

In [13]:
X_train

array([[[[ 32,  27,  26],
         [ 36,  31,  30],
         [ 35,  30,  29],
         ..., 
         [186, 203, 210],
         [184, 200, 207],
         [184, 197, 205]],

        [[ 30,  25,  24],
         [ 37,  32,  31],
         [ 38,  33,  32],
         ..., 
         [186, 203, 209],
         [184, 200, 207],
         [185, 198, 206]],

        [[ 47,  42,  41],
         [ 29,  25,  24],
         [ 53,  49,  48],
         ..., 
         [187, 203, 210],
         [184, 200, 207],
         [184, 199, 207]],

        ..., 
        [[ 47,  41,  40],
         [ 47,  42,  41],
         [ 49,  44,  43],
         ..., 
         [ 29,  16,  11],
         [ 21,   9,   5],
         [ 22,  11,   9]],

        [[ 55,  50,  49],
         [ 54,  49,  48],
         [ 63,  58,  57],
         ..., 
         [ 29,  15,  10],
         [ 20,   9,   4],
         [ 22,  11,   9]],

        [[ 37,  32,  31],
         [ 46,  41,  40],
         [ 43,  38,  37],
         ..., 
         [ 27,  13,   8],
  

In [14]:
import pandas as pd

# save it up as a dataframe if you like
df = pd.DataFrame()
df["labels"]=Y
df["images"]=X
df.to_csv('dataset.csv',index=False)



In [15]:
data=pd.read_csv('dataset.csv')
data.head()

labels                                             images
0       1  [[[ 32  27  26]\r\n  [ 36  31  30]\r\n  [ 35  ...
1       1  [[[120 129 143]\r\n  [120 129 143]\r\n  [119 1...
2       1  [[[204 168 137]\r\n  [228 204 181]\r\n  [165 1...
3       1  [[[ 24  27  32]\r\n  [ 24  27  32]\r\n  [ 24  ...
4       1  [[[ 66  67 105]\r\n  [ 75  76 114]\r\n  [ 86  ...

# Anather  Method

In [16]:
imgs = [image.load_img(img_path, target_size=(200, 200)) for img_path in images_path]
img_array = np.array([image.img_to_array(img) for img in imgs])

In [17]:
img_array

array([[[[  26.,   27.,   32.],
         [  43.,   44.,   49.],
         [  36.,   37.,   42.],
         ..., 
         [ 210.,  203.,  187.],
         [ 208.,  201.,  185.],
         [ 205.,  197.,  184.]],

        [[  27.,   28.,   33.],
         [   5.,    6.,   11.],
         [  27.,   28.,   33.],
         ..., 
         [ 210.,  203.,  187.],
         [ 208.,  201.,  185.],
         [ 206.,  198.,  185.]],

        [[   6.,    7.,   11.],
         [  28.,   29.,   33.],
         [  23.,   24.,   28.],
         ..., 
         [ 210.,  203.,  187.],
         [ 208.,  201.,  185.],
         [ 207.,  200.,  184.]],

        ..., 
        [[  42.,   43.,   48.],
         [  65.,   66.,   71.],
         [  59.,   60.,   65.],
         ..., 
         [   8.,   14.,   28.],
         [   8.,   12.,   24.],
         [   9.,   12.,   21.]],

        [[  43.,   44.,   49.],
         [  36.,   37.,   42.],
         [  47.,   48.,   53.],
         ..., 
         [   6.,   12.,   26.],
       

In [67]:
#Splitting the train_images into the Training set and validation set
from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val= train_test_split(X_train, Y_train,
               test_size=0.2, random_state=42,stratify=Y_train)