### Operations 

In [2]:
1 + 1

2

In [3]:
1 * 3

3

In [4]:
1 / 2

0.5

In [5]:
2 ** 4

16

In [6]:
4 % 2

0

In [7]:
5 % 2

1

In [8]:
(2 + 3) * (5 + 5)

50

### Printing

In [9]:
x = 'hello'

In [10]:
x

'hello'

In [11]:
print(x)

hello


In [13]:
num = 25
name = 'Ahmed'

In [14]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 25, and my name is: Ahmed


In [15]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 25, and my name is: Ahmed


### Lists

In [16]:
[1,2,3]

[1, 2, 3]

In [17]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [18]:
my_list = ['a','b','c']

In [19]:
my_list.append('d')

In [20]:
my_list

['a', 'b', 'c', 'd']

In [21]:
my_list[0]

'a'

In [22]:
my_list[3]

'd'

In [23]:
my_list[1:]

['b', 'c', 'd']

In [24]:
my_list[:1]

['a']

In [25]:
my_list[0] = 'NEW'

In [26]:
my_list

['NEW', 'b', 'c', 'd']

In [27]:
nest = [1,2,3,[4,5,['target']]]

In [28]:
nest[3]

[4, 5, ['target']]

In [29]:
nest[3][2]

['target']

In [30]:
nest[3][2][0]

'target'

In [33]:
del(nest)

In [34]:
nest

NameError: name 'nest' is not defined

### Dictionaries

In [35]:
d = {'key1':'item1','key2':'item2'}

In [36]:
d

{'key1': 'item1', 'key2': 'item2'}

In [37]:
d['key1']

'item1'

### Tuples 

In [38]:
t = (1,2,3)

In [39]:
t[0]

1

In [40]:
t[0] = 'NEW'

TypeError: 'tuple' object does not support item assignment

### Sets

In [41]:
{1,2,3}

{1, 2, 3}

In [42]:
{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3}

## Comparison Operators

In [43]:
1 > 2

False

In [44]:
1 < 2

True

In [45]:
1 >= 1

True

In [46]:
1 <= 4

True

In [47]:
1 == 1

True

In [48]:
'hi' == 'bye'

False

## Logic Operators

In [49]:
(1 > 2) and (2 < 3)

False

In [50]:
(1 > 2) or (2 < 3)

True

In [51]:
(1 == 2) or (2 == 3) or (4 == 4)

True

## if,elif, else Statements

In [52]:
if 1 < 2:
    print('Yep!')

Yep!


In [53]:
if 1 < 2:
    print('first')
else:
    print('last')

first


In [54]:
if 1 > 2:
    print('first')
else:
    print('last')

last


In [55]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


## for Loops

In [56]:
seq = [1,2,3,4,5]

In [57]:
for item in seq:
    print(item)

1
2
3
4
5


In [59]:
for jelly in seq:
    print(jelly+jelly)

2
4
6
8
10


## while Loops

In [60]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


## range()

In [61]:
range(5)

range(0, 5)

In [62]:
for i in range(5):
    print(i)

0
1
2
3
4


In [63]:
list(range(5))

[0, 1, 2, 3, 4]

## list comprehension

In [64]:
x = [1,2,3,4]

In [65]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [66]:
[item**2 for item in x]

[1, 4, 9, 16]

## functions

In [67]:
def sum(x,y):
    """
    Docstring goes here.
    """
    print(x+y)

In [69]:
sum

<function __main__.sum>

In [71]:
sum(45,5)

50


In [72]:
def square(x):
    return x**2

In [75]:
out = square(10)

In [76]:
print(out)

100


## methods

In [79]:
st = 'hello my name is Ahmed'

In [80]:
st.lower()

'hello my name is ahmed'

In [81]:
st.upper()

'HELLO MY NAME IS AHMED'

In [82]:
st.split()

['hello', 'my', 'name', 'is', 'Ahmed']

In [83]:
tweet = 'Go Sports! #Sports'

In [84]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [85]:
tweet.split('#')[1]

'Sports'

In [86]:
d

{'key1': 'item1', 'key2': 'item2'}

In [87]:
d.keys()

dict_keys(['key2', 'key1'])

In [88]:
d.items()

dict_items([('key2', 'item2'), ('key1', 'item1')])

In [89]:
lst = [1,2,3]

In [90]:
lst.pop()

3

In [91]:
lst

[1, 2]

In [92]:
'x' in [1,2,3]

False

In [93]:
'x' in ['x','y','z']

True

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python.



In [94]:
import numpy as np

Numpy Arrays
NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

Creating NumPy Arrays
From a Python List
We can create an array by directly converting a list or list of lists:

In [95]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [96]:
np.array(my_list)

array([1, 2, 3])

In [97]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [98]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods
There are lots of built-in ways to generate Arrays



In [99]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones
Generate arrays of zeros or ones

In [101]:
np.zeros(3)

array([0., 0., 0.])

In [102]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [103]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [104]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.



In [105]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [106]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Creates an identity matrix

In [107]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``

In [108]:
np.random.rand(2)

array([0.47116871, 0.06569604])

In [109]:
np.random.rand(5,5)

array([[0.59302341, 0.22164329, 0.12020492, 0.04110146, 0.65554111],
       [0.67097393, 0.83712352, 0.17236876, 0.22936807, 0.30946591],
       [0.85603539, 0.71571436, 0.12733954, 0.72517492, 0.55515076],
       [0.61161059, 0.95541708, 0.07986083, 0.13893451, 0.36530802],
       [0.45548739, 0.0983995 , 0.26245772, 0.64731128, 0.09623108]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [110]:
np.random.randn(2)

array([0.92984395, 0.80856953])

In [111]:
np.random.randn(5,5)

array([[ 0.24315492,  0.10025682, -0.5772203 , -0.88831907, -1.96523423],
       [ 0.78962848, -1.48821455,  1.50747114, -0.93188245, -1.00166012],
       [ 0.11636065, -1.38521742,  0.30681753, -1.19380877,  2.37083016],
       [ 0.47261447, -1.36246948,  0.237348  , -0.99753224,  0.44139337],
       [ 0.86561499,  1.66237542, -1.98917929, -0.5892411 , -0.7713351 ]])

### randint
Return random integers from low (inclusive) to high (exclusive).

In [112]:
np.random.randint(1,100)

13

In [113]:
np.random.randint(1,100,10)

array([61, 53, 37, 94, 97,  2, 25, 85, 97, 57])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [115]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [117]:
ranarr

array([39, 39, 44,  6,  1, 39, 31, 34,  0, 48])

### Reshape
Returns an array containing the same data with a new shape.

In [118]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [120]:
ranarr.max()

48

In [121]:
ranarr.argmax()

9

In [122]:
ranarr.min()

0

In [123]:
ranarr.argmin()

8

## Shape

Shape is an attribute that arrays have (not a method):

In [125]:
# Vector
arr.shape

(25,)

In [126]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [127]:
arr.reshape(1,25).shape

(1, 25)

In [128]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype
You can also grab the data type of the object in the array:

In [129]:
arr.dtype

dtype('int32')

In [130]:
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    s = 1/(1+np.exp(-x))
    
    return s

In [131]:
def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """

    s = sigmoid(x)
    ds = s*(1-s)
    
    return ds

In [132]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [133]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


### Vectorization

In [155]:
import time

x1 = np.linspace(0,100,5000)
x2 = np.linspace(0,100,5000)
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 16668333.66673333
 ----- Computation time = 15.625ms
gdot = [126114.09421965 123416.46769264 125027.35781688]
 ----- Computation time = 15.625ms


In [156]:
### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 16668333.66673335
 ----- Computation time = 0.0ms
gdot = [126114.09421965 123416.46769264 125027.35781688]
 ----- Computation time = 0.0ms


### Broadcasting 
A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical operations between arrays of different shapes. For the full details on broadcasting, you can read the official [broadcasting documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

In [146]:
w=np.array([[1,2,3,4,5],[1,2,3,4,5]])
z=np.array([1,2,3,4,5])

In [147]:
w+z

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [151]:
w=np.array([[1,2,3,4,5],[1,2,3,4,5]])
z=np.array([[1],[2]])

In [152]:
w+z

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])